type/build:
  - '^build(\(?:.*\))?:'
type/ci:
  - '^ci(\(?:.*\))?:'
type/chore:
  - '^chore(\(.*\))?:'
type/bug:
  - '^bug(?:\(.*\))?:'
type/docs:
  - '^docs(\(?:.*\))?:'
type/deps:
  - '^deps(\(?:.*\))?:'
type/test:
  - '^test(\(?:.*\))?:'
type/upstream:
  - '^upstream(\(?:.*\))?:'
type/feat:
  - '^feat(\(?:.*\))?:'
type/fix:
  - '^fix(\(?:.*\))?:'
type/refactor:
  - '^refactor(\(?:.*\))?:'
