# This file contains manual label matching in-case of where the issue or PR doesn't
# have a conventional-commits title.

type/build:
  - head-branch: ['^build']
  - changed-files:
    - any-glob-to-any-file:
      - 'gradle/*.gradle*'
      - '*.gradle*'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
type/ci:
  - head-branch: ['^ci']
  - changed-files:
    - any-glob-to-any-file:
      - '.github/*'
type/bug:
  - head-branch: ['^bug']
type/docs:
  - head-branch: ['^docs']
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
type/deps:
  - head-branch: ['^deps']
  - changed-files:
    - any-glob-to-any-file:
      - 'gradle/*.versions.toml'
type/test:
  - head-branch: ['^test']
  - changed-files:
    - any-glob-to-any-file:
      - 'src/test/**'
type/upstream:
  - head-branch: ['^upstream']
type/feat:
  - head-branch: ['^feat']
type/fix:
  - head-branch: ['^fix']
type/refactor:
  - head-branch: ['^refactor']
