installer.title=Leaf Installer

option.show.unstable=Show unstable
option.use.proxy=Use proxy

progress.done=Done
progress.done.server=Server successfully installed
progress.download.library.entry=Downloading library {0}
progress.exception.no.launcher.directory=No zomboid directory found!
progress.exception.no.launcher.config=No ProjectZomboid64.json config found!
progress.installing=Installing Leaf Loader {0} on the client
progress.installing.server=Installing Leaf Loader {0} on the server

prompt.exception=Exception
prompt.exception.caused.by=Caused by
prompt.exception.occurrence=Exception occurred!
prompt.exception.suppressed=Suppressed

prompt.install=Install
prompt.install.manual=Install (manual)

prompt.loader.version=Loader Version:
prompt.loading.versions=Loading versions
prompt.game.version=Project Zomboid Version:
prompt.ready.install=Ready to install
prompt.select.location=Game Location:
prompt.install.successful.title=Successfully Installed
prompt.install.successful=Leaf Loader {0} for {1} has successfully been installed.

tooltip.use.proxy=Installs the latest version of the loader proxy instead of the loader itself.

tab.client=Client
tab.server=Server
